# Generated by Django 5.0.7 on 2024-11-06 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FechaHora',
            fields=[
                ('id_fecha_hora', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id_aeropuerto', models.IntegerField(primary_key=True, serialize=False)),
                ('aviones_disponibles', models.IntegerField(blank=True, null=True)),
                ('empleados', models.IntegerField(blank=True, null=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajeros',
            fields=[
                ('rut_pasajero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('id_aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.aeropuerto')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id_checkin', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_checkin', models.DateTimeField(blank=True, null=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
                ('rut_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.pasajeros')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id_transfer', models.IntegerField(primary_key=True, serialize=False)),
                ('destino', models.CharField(blank=True, max_length=60, null=True)),
                ('id_aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.aeropuerto')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaEmbarque',
            fields=[
                ('id_tarjeta_embarque', models.IntegerField(primary_key=True, serialize=False)),
                ('puerta_embarque', models.CharField(blank=True, max_length=5, null=True)),
                ('id_checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.checkin')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pasajeros',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario'),
        ),
        migrations.CreateModel(
            name='ModelosAviones',
            fields=[
                ('id_modelo', models.IntegerField(primary_key=True, serialize=False)),
                ('modelos', models.CharField(blank=True, max_length=60, null=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Equipaje',
            fields=[
                ('id_equipaje', models.IntegerField(primary_key=True, serialize=False)),
                ('peso_equipaje', models.IntegerField(blank=True, null=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
                ('rut_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.pasajeros')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario'),
        ),
        migrations.CreateModel(
            name='Aviones',
            fields=[
                ('id_avion', models.IntegerField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('id_aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.aeropuerto')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
                ('id_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.modelosaviones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Asientos',
            fields=[
                ('id_asiento', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('clase', models.CharField(blank=True, max_length=20, null=True)),
                ('id_avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.aviones')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='aeropuerto',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario'),
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id_vuelo', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_vuelo', models.DateTimeField(blank=True, null=True)),
                ('id_avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.aviones')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajes',
            fields=[
                ('id_pasaje', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=40, null=True)),
                ('id_asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.asientos')),
                ('id_avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.aviones')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.fechahora')),
                ('rut_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.pasajeros')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario')),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.vuelos')),
            ],
        ),
    ]
