# Generated by Django 5.0.7 on 2024-11-21 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_remove_checkin_hora_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='id_vuelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viajes.vuelos'),
        ),
        migrations.AlterField(
            model_name='asientos',
            name='id_asiento',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
